### ISSUE TITLE
error running ./configure after cloning and running ./bootstrap

### ISSUE THREAD

**Issue by edadma** [crosstool-ng/crosstool-ng#1035]
crosstool-NG version: 1.23.0
OS and its version: Linux Mint 19 (based on Ubuntu 18.04)

the last line of output from `./configure` is
```
configure: error: Required tool not found: GNU libtool >= 2.4
```

the solution was to install `libtool-bin` - should be added to the list of required packages for Ubuntu in the section "Setting up host OS" in the docs.

**Comment by stilor** [comment]
Would you mind submitting a full description of how to configure a Mint installation? If you have a Dockerfile, even better.

**Comment by stilor** [comment]
Fixed.

**Comment by pold500** [comment]
It's not fixed, on the page "Setting up host OS" there's no mention of it, also, I would really prefer this page to be in the beginning of the TOC, not in the end.

Also, adding up something like "run sudo apt install -y [all_the_required_packages] would be really nice.
