### ISSUE TITLE
64bit “libwinpthread-1.dll” is missing in the finial installation of target “x86_64-w64-mingw32”

### ISSUE THREAD

**Issue by blkf2016** [crosstool-ng/crosstool-ng#853]
### Issue submission guidelines
See [detaled guidelines](http://crosstool-ng.github.io/support/). In short:
- Report crosstool-NG version
crosstool-ng-1.23.0-240-gaec73d9c

- Report host OS and its version
gentoo linux up to date

- Attach `.config` (unless the issue is not related to any configuration)
https://drive.google.com/open?id=0B0-5yV9_rtB4WDNEdjViOU1EQnc

- Attach `build.log` (unless crosstool-NG fails before the build starts)
https://drive.google.com/open?id=0B0-5yV9_rtB4cElGVy1jZlotdkU

Both 32bit and 64bit binary of "libwinpthread-1.dll" ware generated in the build process. But only  32bit version is installed in the final toolchian directory.

**Comment by stilor** [comment]
Well, that itself wasn't a big mistery: both 32-bit and 64-bit versions install into the same location, so whichever builds last (it is 32-bit) overwrites the first.

The question is why mingw wants to install the a dll into the `bin/` directory rather than `lib/` (or `lib32/`)? My expertise in Windows is quite limited, so I have no idea. @mingwandroid, any chance you might know?

**Comment by ihalip** [comment]
I'm going to take a look at this issue.

**Comment by Cheb57** [comment]
Problem confirmed here and also seen on my side (using tag release 1.23), the install script after building libwinpthread-1.dll's file respectively for x86 and x86-64 if multilib is requested, will overwrite the x86-64 file one. 

To retrieve it, don't clean your build folder and simply copy dll's built respectively from .build/..../lib/ or .build/.../lib32/ about mingw runtime compilation folders. You should browse your build.log ( and grep libwinpthread-1.dll) to find folders were dll files are still located for x86 and x86-64 arch.

**Comment by ihalip** [comment]
I don't see an easy fix for this, but there are a few possible workarounds:

- disable `CT_MULTILIB`

- build libwinpthreads statically so no runtime library is needed

- patch libwinpthreads so that it outputs the runtime library in multiple `bin` directories when building with multilib support

**Comment by stilor** [comment]
Should be fixed by #956. Note that bin/ will still contain a single libwinpthread (although, the default one now). The corresponding lib directory will contain the version as appropriate.

**Comment by Harvie** [comment]
I've just built `x86_64-w64-mingw32,x86_64-pc-linux-gnu` canadian sample using crosstool-ng `1.24.0` on archlinux.
i still get the same error with missing libwinpthread-1.dll.

**Comment by CptMercury** [comment]
I get the same error ### missing libwinpthread-1.dll ### after i built the canadian example ###x86_64-w64-mingw32, arm-cortexa9_neon-linux-gnueabihf### on crosstool-ng ###1.24.0### on ubuntu 20.04.

@Harvie did you find a fix for that issue?

**Comment by Harvie** [comment]
TBH i don't remember after a year, i probably just went with older version or something...

**Comment by CptMercury** [comment]
Alright, thanks for your fast reply
